### ISSUE TITLE
Update mindscape.Raygun4Net.AspNetCore to v6

### ISSUE THREAD

**Issue by Sacrelicious** [serilog/serilog-sinks-raygun#15]
This package has been updated to support the latest configuration method in .NET Core 2.1 (`IConfiguration` vs `IConfigurationRoot`), but unfortunately some classes/namespaces have been moved around so they are no longer the same between Mindscape.Raygun4Net and mindscape.Raygun4Net.AspNetCore (`RaygunClient` is now in `Mindscape.Raygun4Net.AspNetCore` for example). This could be fixed by using some conditional statements based on the framework being used, but that's pretty ugly. It's possible the better solution is to just create a new serilog-sinks-raygun-core package that only targets netstandard2.0.

**Comment by RuaanKruger** [comment]
I just ran into this into a very similar problem because of the namespace difference between `Mindscape.Raygun4Net.AspNetCore` and `Mindscape.Raygun4Net`.

For interest sake, would it not be a better solution to allow the sink to accept a `namespace` parameter and then reflecting the associated Client, Builders and Messages?
